### ISSUE TITLE
Can I use proxy to connect?

### ISSUE THREAD

**Issue by greyyoung** [Bannerets/tdl#10]

**Comment by Bannerets** [comment]
Yes, you can. See https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_proxy.html.

**Comment by greyyoung** [comment]
Thank you @Bannerets . I will try.

**Comment by greyyoung** [comment]
Hi @Bannerets , Do you know any windows GUI app can directly use tdlib db to connect telegram? Thanks.

**Comment by Bannerets** [comment]
@greyyoung unigram

**Comment by greyyoung** [comment]
@Bannerets Thanks
