### ISSUE TITLE
UnhandledPromiseRejectionWarning: #<Object>

### ISSUE THREAD

**Issue by GuilhermeAmado** [Bannerets/tdl#102]
There seems to be an issue when something goes wrong in the connection or auth process with Telegram. You can replicate this error by trying to connect multiple times and make Telegram send the auth code multiple times. After a certain number of times, the connection will be refused and this error appears on the console.

**Comment by Bannerets** [comment]
Sorry for the late reply to your issues. The error is most likely justified (e.g. flooding limits), but you need to catch it. For example, in https://github.com/Bannerets/tdl/issues/101#issuecomment-788268344 replace `connectTelegram()` with `connectTelegram().catch(console.error)` to see what's inside `#<Object>`

**Comment by GuilhermeAmado** [comment]
Yeah, you are right. Sorry for opening a issue. Thanks for the response!
