### ISSUE TITLE
how to remove ', TDLib 1.6.0' from aplication_version value in Telegram session

### ISSUE THREAD

**Issue by alirayaneh** [Bannerets/tdl#104]
hi 
when we create session by tdlib that add extra string to application_version value in telegram session
this is my parameter value
            tdlibParameters: {
                device_model: 'Firefox',
                system_version: 'Windows',
                application_version: '5.7.0',
                enable_storage_optimizer: true,
                apiId: api_id,
                apiHash: api_hash
            }
but when i see telegram sessions 

   application_version: 5.7.0, TDLib 1.6.0

how to caler this copy right

i have used native build from tdlib nativ

**Comment by Bannerets** [comment]
It is not possible without patching TDLib. https://github.com/tdlib/td/blob/a53cb30e99f937cfd64e0266fa558785a184a553/td/telegram/Td.cpp#L4422-L4425
