### ISSUE TITLE
is it possible use java build by this packege ? 

### ISSUE THREAD

**Issue by alirayaneh** [Bannerets/tdl#107]
hi can i use "libtdjni.so" by your repasitory ?
I want to share a Java build file between two different sources.
Is it possible to use  libtdjni.so in your source 
instead libtdjson.so
?

**Comment by Bannerets** [comment]
I don't think it is possible. You can check what it exports via `nm --defined-only -D`. `_td_send` and other functions are required. Sorry for the late reply.
