### ISSUE TITLE
Ghost clients

### ISSUE THREAD

**Issue by vgb0332** [Bannerets/tdl#113]
Hi, first I want to thank you for this library. It's awesome! saving a lot of time :)

There are 2 issues I'm having at the moment.
1. V8 Memory Burst
2. Unknown leftover clients

I'm using the library in Express, where I create one or more instances(already logged in) on HTTP requests, and after finishing with clients, close them accordingly by client.close().

For example,

router.get('/', async (req, res) => {
  var key = getApiKeyFromDB()
  var client1 = new Client({...});
  //Ater done with client1, close
  await client1.close();
  ...
  var client2 = new Client({...});
  ...
  await client2.close();
});

I haven't REALLY tested the problems and how they occur yet (can't find stable error patterns)
But, for issue 1, executing multiple client methods like in a loop, Express crashes throwing bunch of V8 errors, and restart.
For issue 2, in most cases, I think I properly close all the clients, but there are cases where there are yet unknown clients hanging around in the server, or unintentionally crashing into a same client from other processes like node-scheduler.

The memory issue I currently have no idea with it.
But for ghost clients, I wonder if there is a way to check for clients (like client list?) so another process can reuse or close.

**Comment by Roma-Kyrnis** [comment]
Hi, have you found a solutions?

**Comment by Bannerets** [comment]
I don't understand this issue and how all of that is possible, but I welcome a reproducible example.

**Comment by vgb0332** [comment]
> Hi, have you found a solution?

It's been so long i'm not sure if I remember clearly, but
issues came from
1. Memory shortage - each client holds quite some memory while alive.
2. Zombie processes - I later optimized the clients session by handling globally throughout all common processes.

Hope they help.

**Comment by Bannerets** [comment]
Open a new issue if you encounter anything like that (on the latest version).
