### ISSUE TITLE
Dynamic Loading Error: M1 not supported?

### ISSUE THREAD

**Issue by DaviSMoura** [Bannerets/tdl#114]
Hi -- I've compiled TDLib to M1 Pro (arm) and i can't use this lib in node.

Here's the error
![image](https://user-images.githubusercontent.com/48032558/155992828-0e402c31-8fc0-4a7e-9e16-81d5a49522c9.png)

**Comment by Bannerets** [comment]
Hi. Do you use a native Node.js binary, or do you run it using Rosetta (try `node -p "process.arch"`)? Do you run the terminal emulator using Rosetta?

Also make sure that you use Node.js v16 and newer, older versions aren't distributed with native binaries for M1.

**Comment by DaviSMoura** [comment]
Thanks for aswering!

Actually, Im using Node 14 using Rosetta i think.

```
> node -p "process.arch"
x64
```

**Comment by DaviSMoura** [comment]
Updated Node to v16 and arm64.

The error is different now
![image](https://user-images.githubusercontent.com/48032558/156022239-e5af8b34-15b4-46dc-b422-00945cabe473.png)

**Comment by Bannerets** [comment]
Try to reinstall `tdl`, it should recompile the node addon

**Comment by DaviSMoura** [comment]
Worked. Thanks.

Have a great week. :)
