### ISSUE TITLE
setProxy exit program?

### ISSUE THREAD

**Issue by mkliu** [Bannerets/tdl#12]
I'm trying the mult client example. And trying to add a SOCKS5 proxy. Code is like this:

```
await client1.invoke({
    _: 'setProxy',
    proxy: {
      _: 'proxySocks5',
      server: '192.169.233.35',
      port: 24006
    }
  });
```

- I first put this before the client1.connect(). The program just exit directly in this case. 
- If I put it after client1.connect(), after calling setProxy, I could see it's returns {_:'ok'}. However, I doubt it's really getting used because even if I used a wrong proxy, the next call of "getChat" can still return the right result.

An suggestions? Ideally I want proxy to kick in before client even trying to connect

**Comment by Bannerets** [comment]
> if I used a wrong proxy, the next call of "getChat" can still return the right result.

Can't reproduce. When I use wrong proxy, I see `PosixError : Connection refused : 61 : Read from fd 45 has failed` in the console.

If you want to set proxy before authorization, it's not possible right now. Maybe it will be available in next release.

Also, you can use `client.invoke({ _: 'getProxy' })` to get current proxy.

**Comment by mkliu** [comment]
Set proxy call would fail but it could still getChats successfully, coz it’s already connected. I guess if I want to start with proxy, I probably need to set at the machine level then. Let me try that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Bannerets** [comment]
@mkliu Proxy should work correctly, if you set it after `client.connect()`

**Comment by Bannerets** [comment]
In v4.0+ you can set proxy before auth:
```js
const client = new Client({ ... })
await client.connect(() =>
  client.invoke({
    _: 'setProxy',
    proxy: {
      _: 'proxySocks5',
      server: '...',
      port: ...
    }
  })
)
```
