### ISSUE TITLE
Error 400 | Valid api_id must be provided although it is being provided

### ISSUE THREAD

**Issue by IscoV** [Bannerets/tdl#122]
Hello, I do not know what has been changed in the latest versions but it does not allow me to start the script showing me the message of the image attached to this issue. 

I am setting the parameters correctly or this is how they worked in previous versions. 

If someone has the same problem and has found a solution I would be very grateful.

Usage:
- Raspberry Pi 3b+ Rev1.3
- Ubuntu 18.04.5 LTS aarch64

![imagen](https://user-images.githubusercontent.com/53531688/190927001-cc54abff-cb07-42ff-a49a-4381fa524696.png)

**Comment by Bannerets** [comment]
Yes, this is a known issue on TDLib v1.8.6+, which is not supported (see the README). But, surprisingly, I just released `tdl@7.1.0` a minute ago with the support of latest TDLib! So you need to run `npm install tdl@latest`.

**Comment by IscoV** [comment]
What would we do without you? 😇

What a quick, prompt response and solution to the problem is appreciated.

Great job!
