### ISSUE TITLE
arm64 error

### ISSUE THREAD

**Issue by did0824** [Bannerets/tdl#123]
![Screen Shot 2022-09-22 at 5 20 32 PM](https://user-images.githubusercontent.com/37896341/191695888-ff246d27-f28c-4b1c-b700-3f1ea78071e5.png)

Hi, I'm trying to run tdl, but I got this error. Could you help me to solve this problem? I use mac m1 max.

**Comment by Bannerets** [comment]
Hi! `prebuilt-tdlib` does not support arm (this is stated in the README). You need to build TDLib from the source: https://github.com/tdlib/td#building and install it onto the system (`cmake --install .`), then uninstall `prebuilt-tdlib`.

**Comment by did0824** [comment]
It works well! Thank you for the answer.
