### ISSUE TITLE
Hi. I want asking about bot

### ISSUE THREAD

**Issue by did0824** [Bannerets/tdl#125]
I tried to loginAsBot. And I send messages, that is sent by me not from bot.
Could tell me possible way for send message as bot?
And other invoke method can be done by bot too?

**Comment by Bannerets** [comment]
> that is sent by me not from bot.

It could be that you were already logged in as a user, try to remove the database (`rm -rf _td_database _td_files`) and launch the script again.

**Comment by did0824** [comment]
Thank you. Is there way to know that method is available for bot?
