### ISSUE TITLE
can someone help me with updateUser?

### ISSUE THREAD

**Issue by thihakyaw** [Bannerets/tdl#127]
I am trying to update logged in user username and first name using tdl.

//@description Some data of a user has changed. This update is guaranteed to come before the user identifier is returned to the application @user New data about the user
updateUser user:user = Update;

Can someone provide me example code for it? The documentation is complicated.

The invoke method for updateUser I was trying to call the class is following this. The authentication part is already done and I can call getMe class and some other classes.
```
await client.invoke({
        _: 'updateUser',
        user: {
            first_name: "Thiha"
        }
})
```
The error message I got is -
```
{
  _: 'error',
  code: 400,
  message: 'Failed to parse JSON object as TDLib request: Unknown class "updateUser"'
}
```

**Comment by Bannerets** [comment]
`updateUser` is not a function (`update` is not a verb here), it's an update you can receive if some of the data was changed on the server. The callable functions are listed after `---functions---` in the tl file. I think you need to use `setUsername` and `setName` instead.

**Comment by thihakyaw** [comment]
This works well. Thanks for clarifying !

**Comment by smff** [comment]
can u add a some examples for user profile photo?
