### ISSUE TITLE
Channel topic name quest 

### ISSUE THREAD

**Issue by AktilaCengiz** [Bannerets/tdl#132]
Hello i am using this package but i cant find how can i acess channel topic ? I am using getChannel but doesnt return with thread channel name. Just return with thread_channel_id. How can i resolve thread channel id and acess topic name. Can you help me? Best regards, Aktila.

**Comment by Bannerets** [comment]
if you mean topics/forums in supergroups, it's called `ForumTopics` in tdlib, there's a [getForumTopics](https://github.com/tdlib/td/blob/b844da31d43b5a66853a6c1ed9d06d437a8c247a/td/generate/scheme/td_api.tl#L6432) method. [getForumTopic](https://github.com/tdlib/td/blob/b844da31d43b5a66853a6c1ed9d06d437a8c247a/td/generate/scheme/td_api.tl#L6420) can return the topic with its name using `chat_id` + `message_thread_id`.
