### ISSUE TITLE
Unknown class "uploadFile"

### ISSUE THREAD

**Issue by omarmyousef** [Bannerets/tdl#135]
whenever i try to invoke the class "uploadFile" this error shows up:
`{
    _: 'error',
    code: 400,
    message: 'Failed to parse JSON object as TDLib request: Unknown class "uploadFile"'
}`

Class reference in the tdlib docs: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1upload_file.html

i've tried to change tdlib version to v1.8.12 using the prebuilt versions here: https://github.com/ForNeVeR/tdlib.native/releases
but that didn't fix the issue

my invoke code:
`upload = await this.client.invoke({
    _: 'uploadFile',
    file: {
        _: 'inputFileLocal',
        path: item.params.file
    }
});`

Thanks in advance and i appreciate your work guys

**Comment by omarmyousef** [comment]
thanks for explaining
i wonder if there's an updated docs for tdlib

**Comment by Bannerets** [comment]
Usually one just browses the tl file

**Comment by omarmyousef** [comment]
Thanks <3
