### ISSUE TITLE
[Question] Event list ?

### ISSUE THREAD

**Issue by KaKi87** [Bannerets/tdl#137]
Hello,

The README mentions two events, `update` and `error` :

https://github.com/Bannerets/tdl/blob/1e1401e3ad63514c262958de010797ededc58d8f/README.md?plain=1#L162-L175

Would it be possible to write an exhaustive list ?

Thanks

**Comment by Bannerets** [comment]
Since tdl v8.0.0, all other events except `close` are removed, and `close` is documented.

**Comment by KaKi87** [comment]
Then now to listen to messages ?

And how are errors now managed ?

Thanks

**Comment by Bannerets** [comment]
I meant "other [than update or error]", sorry, so `update`, `error`, and `close` are now left. (The other ones were too advanced / deprecated.)

**Comment by KaKi87** [comment]
Okay, but then how to receive messages ?

Thanks

**Comment by Bannerets** [comment]
Using the `update` handler (and filtering for `updateNewMessage`) or the recently added `client.iterUpdates`.
