### ISSUE TITLE
process is not defined ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Alkondr223322** [Bannerets/tdl#138]
newbie here, pls don't laugh
I'm trying to use this library in my React application
so I've created a new React project using create-react-app
I've installed tdl, tdl-tdlib-addon, prebuilt-tdlib@td-1.8.12
I've modified my App.js to look like this

`import './App.css';
import { useEffect } from 'react';
const { Client } = require('tdl')
const { TDLib } = require('tdl-tdlib-addon')

const { getTdjson } = require('prebuilt-tdlib')
const tdlib = new TDLib(getTdjson())

function App() {
  useEffect(() => {
    const telegramLogin = async function() {
      const client = new Client(tdlib, {
          apiId: process.env.APP_ID, // Your api_id
          apiHash: process.env.APP_HASH // Your api_hash
      })
      await client.login()
      return client;
    }

    const client = telegramLogin();
    console.log(client);
  }, []);
  return (
    <div className="App">
      <header className="App-header">

      </header>
    </div>
  );
}

export default App;`

but I'm getting 
![image](https://github.com/Bannerets/tdl/assets/60030514/44f12629-47bd-4faf-8046-79761fc2bed2)

at

![image](https://github.com/Bannerets/tdl/assets/60030514/0a896c2e-900b-4751-8632-1d50a3efda8a)

Is there a way to fix this? Or am I just using this library incorrectly, since this code worked fine when I used it in Express app

`const express = require("express");
const mongoose = require("mongoose");
const path = require("path");
const config = require("./config");
const cors = require('cors');
const PORT = process.env.PORT || 3000;
const { Client } = require('tdl')
const { TDLib } = require('tdl-tdlib-addon')

const { getTdjson } = require('prebuilt-tdlib')
const tdlib = new TDLib(getTdjson())

const app = express();
app.use(cors());
app.use(express.static(path.join(__dirname, "tdlib")));
require('dotenv').config()

const telegramLogin = async function() {
    const client = new Client(tdlib, {
        apiId: process.env.APP_ID, // Your api_id
        apiHash: process.env.APP_HASH // Your api_hash
    })
    await client.login()
    return client;
  }

  const start = async function() {
    try {
      //await mongoose.connect(config.MONGO_URI);
      app.listen(PORT, () => {
        console.log("Server has been started...");        
      });
    } catch (e) {
      console.log(e);
    }
    const client = await telegramLogin();
    const chats = await client.invoke({
        _: 'getChats',
        chat_list: { _: 'chatListMain' },
        limit: 4000
      })
    console.log(chats)

  }
start();`

**Comment by Bannerets** [comment]
Well, the library (especially `prebuilt-tdlib`) only works in Node.js, not in the browser. For the browser, try tdweb https://www.npmjs.com/package/tdweb, though it wasn't updated in a while.

**Comment by Alkondr223322** [comment]
> Well, the library (especially `prebuilt-tdlib`) only works in Node.js, not in the browser. For the browser, try tdweb https://www.npmjs.com/package/tdweb, though it wasn't updated in a while.

Got it, I'll keep it on server side then, thank you
