### ISSUE TITLE
Unable to auth with prebuilt-tdlib with in Docker container

### ISSUE THREAD

**Issue by faisal3389** [Bannerets/tdl#140]
##### Package info:
"tdl": "^7.3.1"
"prebuilt-tdlib": "^0.1008014.0",
OS:	Ubuntu 22.04.2 LTS
Node: v18.16.1

### Description:

When I run the node app with tdl locally on Ubuntu I'm able to configure `tdjson` with `getTdjson()` and the auth is successful with apiId and apiHash. and show the following logs

`[ 2][t 3][168430.946344044][AuthDataShared.cpp:112][#1][!Td]	DcId{5} [auth_key_id:1492480616461][state:OK][created_at:168810600][last_used:168879006]
[ 2][t 3][168872430.95574473][Session.cpp:269][#1][!SessionProxy:5:main]	Generate new session_id 7148724116159533 for auth key 14492480863616461 for main DC5`

But when I try to do the same inside an Ubuntu container the auth fails with logs which look something like 
` [ 2][t 4][1688798680.3301103][Timer.cpp:67][#1][!RunOnSchedulerWorker][&duration > max_duration_]	SLOW: [name:Encrypt SQLite database][duration:100.7ms]
telegram-server_1  | [ 2][t 4][1688798680.39570361][TdDb.cpp:382][#1][!RunOnSchedulerWorker]	Set PRAGMA user_version = 14
telegram-server_1  | [ 2][t 1][1688798680.401883324][AuthDataShared.cpp:112][#1][!Td]	DcId{1} [auth_key_id:0][state:Empty][created_at:0][last_used:0]
telegram-server_1  | [ 2][t 1][168873680.4613431][Session.cpp:269][#1][!SessionProxy:1:main]	Generate new session_id 12330819553617 for auth key 0 for main DC1
Please enter your phone number
`

I also tried to use Ubuntu Image instead of Docker Node18 image which runs on Debian. but the problem still persists. 

Any suggestions how I can resolve this. Thank you!

**Comment by Bannerets** [comment]
The auth actually doesn't fail, it just asks for the phone number in the console because you're not logged in and that's the default in `client.login` (though the prompt for it is a bit intertwined with other logs, see the `Please enter your phone number:` line). You can enter the login details if you launch the container with `-it` or similar, or override functions in `client.login` (as indicated in the README) so it doesn't ask in the console.

**Comment by faisal3389** [comment]
Thanks for the reply, 

with the same code of `client.login` when I run the code directly the prompt `Please enter your phone number:` doesn't come in the terminal. I was wondering what is the difference when I run the code in terminal vs via docker.

also this log is different in both cases:
`DcId{5} [auth_key_id:1492480616461][state:OK]`

vs 

`DcId{1} [auth_key_id:0][state:Empty][created_at:0][last_used:0]`

**Comment by Bannerets** [comment]
I guess that's because you're already logged in on your device (the data is stored in the `_td_database` directory, by default), but not in the container.

**Comment by faisal3389** [comment]
Ah, Got it, thanks for the explanation. Will try to send phone number and auth code to see if it works. Thank you.

**Comment by faisal3389** [comment]
This worked, closing the issue. Thanks again!
