### ISSUE TITLE
"Inline keyboard expected" when using keyboardButtonTypeRequestUser in reply markup

### ISSUE THREAD

**Issue by AB-70** [Bannerets/tdl#145]
Hi, I have been trying to use the telegram's recent bot feature that let's you select chats or users using the new intuitive UI. The bot is supposed to receive the chat identifier as a service message after the chat or user has been selected by the user. 

However, I have been constantly facing this issue when trying to send the `keyboardButtonTypeRequestUser` inside the reply markup. 

Here is the example code: 
```
await client?.invoke({
  _: "editMessageText",
  chat_id: chatId,
  message_id: messageId,
  input_message_content: { _: "inputMessageText", text: parsedMenuText },
  reply_markup: {
    _: "replyMarkupShowKeyboard",
    rows: [
      [
        {
          _: "keyboardButton",
          text: "Select user",
          type: {
            _: "keyboardButtonTypeRequestUser",
          },
        },
      ],
    ],
  },
});
```

The error message: 
`{"_":"error","code":400,"message":"Inline keyboard expected"}`

Expected behavior: 
Message with inline button that allows user/chat selection.

What I have tried so far: 
- Using `inlineKeyboardButton` instead of `keyboardButton`, ignoring the type errors - no luck.
- Using `replyMarkupInlineKeyboard` instead of `replyMarkupShowKeyboard` - no luck. 

Note: The issue seems to be with both `keyboardButtonTypeRequestUser` and `keyboardButtonTypeRequestChat`. 

Any help will be much appreciated. :) 

My Environment
- tdl version: `7.3.2`
- prebuilt-tdlib: `0.1008014.0`
- tdl-tdlib-addon: `1.2.2`
- tdlib-types: `0.1001008014.0`
- typescript: `5.2.2`
- NodeJS: `18.17.1`
- NPM Version: `9.6.7`
- OS: `Win 11`

**Comment by Bannerets** [comment]
Hi, if I'm not mistaken, you can only change inline keyboards when editing a message, so you probably should send a new message with the request. Also, I think you need to add the `id` field to `keyboardButtonTypeRequestUser` for the request to be correct (the optional/required property isn't always explicitly stated in the doc).

**Comment by AB-70** [comment]
Oh man, thank you so much. That worked! Crazy how it's not mentioned anywhere or I just did not see it!
