### ISSUE TITLE
How can I use multiple clients?

### ISSUE THREAD

**Issue by Roma-Kyrnis** [Bannerets/tdl#150]
Hi,

I need to create a message scheduler in Telegram. Users log in to TDLib and set a message that will be sent to chats periodically. Users log in through the chatbot (Grammy). I need to have in memory a lot of `Client` instances. And I have only one bot that interacts with each Client instance independently

I have at least two issues with multi clients:
- `A closed client cannot be reused, create a new Client`
- after sending the request `getChats`, bot is not receiving updates and waiting for `getChats` function to respond. I tested that TDLib client still receiving updates while bot (grammy) is waiting.

I can help to improve the examples, docs, and code if needed for improving or implementing multi-client features.

I'm using TDLib with Grammy bot. *Flow*:
1. User sends /start command to the bot
2. Bot send auth request to TDLib
3. The bot asks some questions to pass the auth state in TDLib
4. After the user is logged in. The bot responds with a Custom keyboard.
5. The user clicks a button on the keyboard go to another keyboard "chats" then click on the button "add"
6. Button will trigger Hear "chatsAddHears".
7. In this process I get Grammy logs but nothing specials. After a 3-5 times of repeating clicking the "chatsAddHears" button - bot stops responding
8. It happened on the customer side. I don't have this issue. But after bot stops on customer side, bot stops to respond to every one.

![Screenshot from 2024-01-25 15-45-28](https://github.com/Bannerets/tdl/assets/56438694/521fe742-37d0-4492-a28c-ae5b66c156f8)
But now I get error:
![Screenshot from 2024-01-26 11-18-43](https://github.com/Bannerets/tdl/assets/56438694/959b3dec-a9a5-43bf-94f1-a8ef4db48439)

On every boot, I create a `new Client` instance and put it inside the `Map`.
On every shutdown, I stop every instance and clear them all.

I've used:
export DEBUG = "grammy*".

<details>
<summary> chatAddHears </summary>

``` typescript
export const chatsAddHears: HearsMiddleware<MyContext> = async (ctx: MyContext): Promise<void> => {
  const telegramId = ctx.from?.id;
  if (!telegramId) {
    await ctx.reply('You does not have permission to enter the bot without ID.');
    return;
  }

  const client = getTDLibInstanceDB(telegramId);
  if (!client) {
    await ctx.reply(`Будь-ласка перевірте чи ви увійшли в додаток Телеграму`);
    return;
  }

  console.log('client', client);
  const chats = await client.getChatsWithInfo();
  console.log('client.getChatsWithInfo', chats);
  const sortedChats = chats.map(chat => [
    chat.title,
    constantsConfig.CHATS.CALLBACK_QUERY.CHOOSE_CHAT + chat.id.toString(),
  ]);
  console.log('chats.map', sortedChats);
  const keyboard = chooseChatKeyboard(sortedChats);
  console.log('chooseChatKeyboard', keyboard);

  await ctx.reply(stringToMarkdownV2(ua.RESULT_TEXT.CHATS.GET_BUTTONS_KEYBOARD), {
    reply_markup: keyboard,
    parse_mode: 'MarkdownV2',
  });
};
```
</details>

Last crash with more logs:
![image](https://github.com/grammyjs/grammY/assets/56438694/c82a2290-9105-4a08-928c-95d1b03e0b35)

<details>
<summary> Overall code execution </summary>

``` typescript
const bot = new Bot<MyContext>(env.TELEGRAM_BOT_TOKEN);

bot.use(
  session({
    initial() {
      // return empty object for now
      return {};
    },
  }),
);
bot.hears(ua.HEARS.CHATS.ADD, chatsAddHears);

/** import { getTDLibInstanceDB } from '../../db/memory/tdlib-instances.ts'; */
import { TDLibInstance } from '../../tdl/main.ts';

const instances = new Map<number, TDLibInstance>();

export const addTDLibInstanceDB = (telegramId: number, instance: TDLibInstance): void => {
  console.log('addTDLibInstanceDB');

  instances.set(telegramId, instance);
};

export const getTDLibInstanceDB = (telegramId: number): TDLibInstance | undefined => {
  console.log('getTDLibInstanceDB');

  return instances.get(telegramId);
};


/** getChatsWithInfo */
async function getChatsWithInfo(client: tdlClient, limit?: number): Promise<Td.chat[]> {
  const chats = await getChats(client, limit);
  console.log('getChatsWithInfo', chats);

  const chatsWithInfo = [];
  for (const chatId of chats.chat_ids) {
    const chat = await getChat(client, chatId);
    chatsWithInfo.push(chat);
  }

  return chatsWithInfo;
}

/** import { chatsKeyboard, chooseChatKeyboard } from '../keyboards/chats.ts'; */
import { InlineKeyboard, Keyboard } from 'grammy';

import constantsConfig from '../../config/constants.config.ts';
import ua from '../../config/locales/ua.ts';

export const chatsKeyboard = new Keyboard()
  .text(ua.HEARS.CHATS.ADD)
  .row()
  .text(ua.HEARS.CHATS.LIST)
  .row()
  .text(ua.HEARS.CHATS.REMOVE)
  .row()
  .text(ua.HEARS.BACK_TO_MAIN_MENU)
  .resized();

/**
 * const labelDataPairs = [
  ['« 1', 'first'],
  ['‹ 3', 'prev'],
  ['· 4 ·', 'stay'],
  ['5 ›', 'next'],
  ['31 »', 'last'],
];
 *
 * Limit is 100 buttons in telegram
 *
 * @param labelDataPairs array of buttons where label is what user see and data is what you will get on user's callback. For label better user Name of the Chat and for Data ChatId
 * @returns InlineKeyboard that you can reply to user
 */
export const chooseChatKeyboard = (labelDataPairs: string[][]): InlineKeyboard => {
  const buttonRow = labelDataPairs.map(([label, data]) => [InlineKeyboard.text(label, data)]);
  console.debug('buttons.length', buttonRow.length);

  if (buttonRow.length <= constantsConfig.TDLIB.REPLY_MARKUP_LIMIT_BUTTONS) {
    return InlineKeyboard.from(buttonRow);
  }

  return InlineKeyboard.from(
    buttonRow.slice(0, constantsConfig.TDLIB.REPLY_MARKUP_LIMIT_BUTTONS - 1),
  );
}
```
</details>

Can you point me to where I need to look to resolve the issue?

**Comment by Bannerets** [comment]
> `A closed client cannot be reused, create a new Client`

That must be an error somewhere in your code; a client method gets called after `close()`.

For the other ones, can you try to set `tdl.configure({ useNewTdjsonInterface: true })` (before creating clients)?

**Comment by Roma-Kyrnis** [comment]
Yes, I'll try to set it. And I have some ideas what's can happen here:
- I don't need to wait for a response in the Grammy bot from a TDLib client.
- Another one forgot for now. If I'll remember I'll write )

Also, I've updated a lib on my own because I have a little issue with authorization
You can reproduce the issue here: https://github.com/Roma-Kyrnis/tdl-test-examples
You can check updates here: https://github.com/Roma-Kyrnis/tdl/tree/rk/TdlToTsWithoutPrompt/packages/tdl-ts

**Comment by Roma-Kyrnis** [comment]
I've sent a reproducible issue because I can have the same issue now when the bot stops to response and wait `getChats` from TDLib

**Comment by Roma-Kyrnis** [comment]
I'll be gone for 1-2 months. Thank you for your response. If I'll continue I'll write here)
