### ISSUE TITLE
[Help needed] I can't find the tdjson.dll for Windows

### ISSUE THREAD

**Issue by rubenalonsoes** [Bannerets/tdl#151]
Hi!
I'm trying run an prebuilt-tdlib example but I have this error. It seems that tdjson library is not found, but I don't know where is. It should be in some directory of the project?

![image](https://github.com/Bannerets/tdl/assets/1971311/41092f1a-6a87-4dde-9149-d24a9727f12d)

Thanks in advance!

**Comment by Bannerets** [comment]
The examples are meant to be copied and executed inside your project (after installing modules `tdl` and `prebuilt-tdlib`), not directly from this repository, sorry. If you install prebuilt-tdlib from npm, the library will be there. The repository itself doesn't contain any binaries.

**Comment by rubenalonsoes** [comment]
> The examples are meant to be copied and executed inside your project (after installing modules `tdl` and `prebuilt-tdlib`), not directly from this repository, sorry. If you install prebuilt-tdlib from npm, the library will be there. The repository itself doesn't contain any binaries.

Ok, thanks!

**Comment by Bannerets** [comment]
Closing this then, reopen if you still encounter any issues.
