### ISSUE TITLE
When send voicenote with own client official desktop telegram shows it strange 

### ISSUE THREAD

**Issue by unityatadev** [Bannerets/tdl#153]
Do you have example to send voicenote ?(voice message)
Im trying to send it like this with own client :
 `_: this.type,
            voice_note: {
                _: 'inputMessageVoiceNote',
                path: this.path,
                mime_type:'audio/ogg'
            },
            duration:2,
            waveform:null,
            caption:null`
 here type is inputMessageVoiceNote . But here something strange happening . 
On Telegram Desktop, the first time I saw the voice message , I can play it . After the first launch, it became like this ![еуеу](https://github.com/Bannerets/tdl/assets/146160344/2c50685a-882c-4312-ad03-73fd8ad97f75)   icon changed
 and i cant replay it . When I click it it opens audio in mediaplayer in pc .  On phone all is good I can replay it . 

Why I think that it because of code ? When I send voice message with official tg client I can get normal voice message in tg desktop I can replay it.
Also do you have example of how get waveform ? or I cant do it with this library and need do it with my own?

**Comment by Bannerets** [comment]
Resolved in https://github.com/tdlib/td/issues/2850
