### ISSUE TITLE
How to click to an inline button

### ISSUE THREAD

**Issue by boygiandi** [Bannerets/tdl#154]
I got a message that contain inline button. How to click this button by tdl library?

**Comment by boygiandi** [comment]
something like this but javascript
https://stackoverflow.com/questions/56923326/how-to-answer-on-replymarkup-using-telegram-java-tdapi

**Comment by Bannerets** [comment]
Try something like

```javascript
const data = /* get data from msg.reply_markup.rows[x][y].type.data (if ...type._ equals to 'inlineKeyboardButtonTypeCallback') */
await client.invoke({
  _: 'getCallbackQueryAnswer',
  chat_id: /* ... chat id ... */,
  message_id: /* ... message id ... */,
  payload: {
    _: 'callbackQueryPayloadData',
    data
  }
})
```

**Comment by Bannerets** [comment]
Open a new issue or ask in `t.me/tdlibchat` (for TDLib specifics) if one has further questions.
