### ISSUE TITLE
How to call other methods

### ISSUE THREAD

**Issue by erfanmola** [Bannerets/tdl#155]
Hi, my question might be completely unrelated to TDLib, but there are some methods like `messages.requestWebView` that are not part of TDLib, how can we call them?

**Comment by Bannerets** [comment]
The methods of the telegram client api cannot directly be called in TDLib; instead, TDLib provides its own api (the schema of which can be found in https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) with wrappers over them.

So to request a web view, it looks like you need to use the [openWebApp](https://github.com/tdlib/td/blob/969bde99c120e71f6221135fc148a0fefdaff26c/td/generate/scheme/td_api.tl#L8753) method.
