### ISSUE TITLE
Add more than one account

### ISSUE THREAD

**Issue by alex-mxrz** [Bannerets/tdl#156]
Hello, question about possibility to add more than one telegram account without create different instance, I try to google, but doesn't found clear answer.

**Comment by Bannerets** [comment]
You need to create a client per account, as shown in a small [multiple-accounts.js](https://github.com/Bannerets/tdl/blob/e57cd52b6462d0c230194b24e44e246900e9a234/examples/multiple-accounts.js) example.

**Comment by alex-mxrz** [comment]
> You need to create a client per account, as shown in a small [multiple-accounts.js](https://github.com/Bannerets/tdl/blob/e57cd52b6462d0c230194b24e44e246900e9a234/examples/multiple-accounts.js) example.

Thanks for the answer, that's so sad, also when creating 2 instances of client in same directory, it don't lead to unexpected errors?

**Comment by Bannerets** [comment]
database directories should be different. what's the issue with creating multiple clients?

**Comment by alex-mxrz** [comment]
After some tests, all work fine.
