### ISSUE TITLE
The updateNewMessage event is not triggered unless you enter the message in the Telegram application and see it. 

### ISSUE THREAD

**Issue by AktilaCengiz** [Bannerets/tdl#159]
The update New Message event will not be triggered unless you enter the message into the Telegram application.

1. Run on a telegram self bot on a VDS.
2. Listening to channel A with upateNewMessageEvent
3. If triggered send a B channel Message (but its not a working)
4. enter the channel via the application (if i want to work 3. steps enter channel via app)
5. send a B channel message send

tdLİB version: 1.8.9
tdl version: 8.0.0
os: windows server

**Comment by Bannerets** [comment]
Try updating TDLib to the latest version and/or call `openChat` on the needed channel. Similar issues have been reported in the TDLib's issue tracker before, see e.g. https://github.com/tdlib/td/issues/2695.

**Comment by Bannerets** [comment]
I see that you also created https://github.com/tdlib/td/issues/2924, I guess it is better tracked there.
