### ISSUE TITLE
QR Code Login with auth.exportLoginToken

### ISSUE THREAD

**Issue by tahpot** [Bannerets/tdl#169]
How do I login using the QR Code Login flow?

https://core.telegram.org/method/auth.exportLoginToken

I've tried a few things, but can't get it to work.

This was my best hope, but it doesn't work:

```
 const response = await client.invoke({
            _: 'auth.exportLoginToken',
            api_id: this.config.apiId,
            api_hash: this.config.apiHash
        });
```

```
TDLibError: Failed to parse JSON object as TDLib request: Unknown class "exportLoginToken"
```

**Comment by Bannerets** [comment]
First of all, for methods you can call in TDLib, see the https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl file in the TDLib repository. The methods on `core.telegram.org/method/` is a different API.

You need to use the `requestQrCodeAuthentication` method. Though, as stated in the tdl's README, the built-in `client.login` function supports only a subset of available methods, and you need to implement the login process yourself. See `examples/custom-login.js` and https://core.telegram.org/tdlib/getting-started#user-authorization. The `requestQrCodeAuthentication` method should be called after an update with `authorization_state = authorizationStateWaitPhoneNumber` is received, as noted in the TDLib documentation.
