### ISSUE TITLE
Usage with Bot API

### ISSUE THREAD

**Issue by kravetsone** [Bannerets/tdl#173]
hello! Is it possible and safe to use your library without disconnecting from the Bot API? For a couple of methods without events handling

**Comment by Bannerets** [comment]
It is used that way apparently without any issues in some bots (`QuotLy` is a large bot that uses tdlib (tdl) and bot api side-by-side; tdlib is used primarily for the `getMessages` method). Though, it is not necessarily safe: it is known that controlling a bot with multiple sessions may lead to loss of some of the updates (you can search for discussions in `@tdlibchat`).

**Comment by kravetsone** [comment]
> It is used that way apparently without any issues in some bots (`QuotLy` is a large bot that uses tdlib (tdl) and bot api side-by-side; tdlib is used primarily for the `getMessages` method). Though, it is not necessarily safe: it is known that controlling a bot with multiple sessions may lead to loss of some of the updates (you can search for discussions in `@tdlibchat`).

Thanks for the answer! It is sad that possibility of missing updates exists( it will be fine to use tdlib for some missing features

**Comment by Bannerets** [comment]
FYI, another option might be to run a bot api server locally that is modified to expose the needed methods (e.g., there is https://github.com/tdlight-team/tdlight-telegram-bot-api).
