### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by panda2048** [Bannerets/tdl#2]
Hi @Bannerets 

I found that you have a similar project and I can see more details with verbositiyLevel: 10 with your lib
Any idea what is going wrong?
Thanks

[ 3][t 1][1527994939.187509060][Td.cpp:4633][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}

[ 7][t 1][1527994939.192461252][Td.cpp:4771][!Td][&td_init]	Begin to set TDLib parameters
[ 7][t 1][1527994939.192550898][Td.cpp:4796][!Td][&td_init]	Fix parameters...
[ 7][t 1][1527994939.192634106][Td.cpp:4723][!Td][&td_init]	Fix use_chat_info_db
[ 7][t 1][1527994939.192690134][Td.cpp:4727][!Td][&td_init]	Fix use_file_db
[ 7][t 1][1527994939.192772150][Td.cpp:4798][!Td][&td_init]	Check binlog encryption...
[ 3][t 1][1527994939.192883968][Binlog.cpp:340][!Td]	Load: init encryption
[ 7][t 1][1527994939.192950010][Td.cpp:4802][!Td][&td_init]	Init alarm multitimeout...
[ 7][t 1][1527994939.192986965][Td.cpp:4806][!Td][&td_init]	Create Global
[ 7][t 1][1527994939.193028212][Td.cpp:4811][!Td][&td_init]	Create MtprotoHeader
[ 7][t 1][1527994939.193070173][Td.cpp:4837][!Td][&td_init]	Send authorizationStateWaitEncryptionKey
[ 7][t 1][1527994939.193114996][Td.cpp:4841][!Td][&td_init]	Finish set parameters
[ 3][t 1][1527994939.193159103][Td.cpp:4633][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitEncryptionKey {
    is_encrypted = true
  }
}

[ 3][t 1][1527994939.195223093][Td.cpp:4648][!Td][&td_requests]	Sending result for request 1: ok {
}

[ 7][t 1][1527994939.198026180][Td.cpp:4413][!Td][&td_init]	Begin to init database
[ 3][t 1][1527994939.198328257][Binlog.cpp:340][!Td]	Load: init encryption
[ 4][t 1][1527994939.198956013][SqliteDb.cpp:177][!Td]	ENCRYPT
Segmentation fault

**Comment by Bannerets** [comment]
Hi. Take a look at https://github.com/tdlib/td/issues/259
