### ISSUE TITLE
How to set proxy in China and Russia need proxy before connect?

### ISSUE THREAD

**Issue by bruce6771** [Bannerets/tdl#22]
socket5 proxy
mtproto proxy
how can i set proxy in client.connect()? HELP

**Comment by Bannerets** [comment]
In v4.x.x version (currently latest stable):
```js
const { Client } = require('tdl')
const client = new Client({ ... })
await client.connect(() => {
  return client.invoke({
    _: 'addProxy',
    server: '...',
    port: '443',
    enable: true,
    type: { _: 'proxyTypeMtproto', secret: '...' }
  })
})
```

For v5.x.x version see [example](https://github.com/Bannerets/tdl/blob/56d9bd45c9438eba84c7653c5625fca60b79c34f/examples/with-proxy.js).
