### ISSUE TITLE
Failed to parse

### ISSUE THREAD

**Issue by Vladyslav120604** [Bannerets/tdl#23]
Hi,
When I сall method getContacts I have this error: 

> `[ 1][t 0][1538770932.840765238][ClientJson.cpp:76][&status.is_error()]Failed to parse [request{\0042@type\0042:\0042getContacts\0042,\0042@extra\0042:\00427597a042f9f94435a90bcd20e19a6c7e\0042}] [Error : 0 : Unknown class]
`

I call this method like this:
`await client.invoke({
        _: "getContacts"
    })
`

**Comment by Bannerets** [comment]
You must have tdlib v1.3.0 to use this method.

**Comment by Vladyslav120604** [comment]
Thanks a lot

**Comment by CryptoSharon** [comment]
Hmmm, how do you update? @Bannerets I never thought I'd have to. This such a complex library to install! Is it the DLLs next to the files (tdjson and zlib1)?

**Comment by Bannerets** [comment]
@CryptoSharon 

> Is it the DLLs next to the files (tdjson and zlib1)?

Yes.

You need to manually compile tdlib https://github.com/tdlib/td#building (in the end you'll get dlls) OR use prebuilt binaries like this https://github.com/ForNeVeR/tdlib.native/releases
