### ISSUE TITLE
Client does not support session resuming which leads to a state when the client is unable to authenticate

### ISSUE THREAD

**Issue by david-benes** [Bannerets/tdl#24]
Steps to reproduce:
1. write a simple script that connects and calls login()
2. run the script
3. wait until Enter Code prompt is displayed
4. break with Ctrl+C
5. start the script again immediately

What happens:
No prompt is displayed.

What should happen
Enter Code prompt should appear or at least an event for resuming a session should be generated.

Analysis:
It seems that the default behavior of TDL library (.so) is to resume previous session when stopped in the middle of authentication. The client (nodejs) does not implement this flow at all and get stuck without ability to do authentication properly.
The problem is that immediately after connect() is called, an event `authorizationStateWaitCode` is generated. This happens even without calling login(). The Client does not expect this. Calling login will cause indefinite waiting for `authorizationStateWaitPhoneNumber` which will never happen (TDL already knows the phone number from previous script run).

Suggestion:
There must be a way to specify login/auth promises before calling login (in Options for example). In case when `authorizationStateWaitCode` appears before calling login, we can call getAuthCode() method specified by the user.

**Comment by Bannerets** [comment]
Thanks. Fixed in v5.0.1.

**Comment by david-benes** [comment]
Awesome! Thanks.
It works perfectly.
