### ISSUE TITLE
How to extract TD database data?

### ISSUE THREAD

**Issue by misha-sen** [Bannerets/tdl#26]
TDLib cashes some data to DB i.e. it saves external user's  [access hashes](https://core.telegram.org/type/User)

And when we trying to call something that affect user_id i.e. [getUserFullInfo](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_user_full_info.html) we'll got "user not found" error if TDLib not saves user's `access_hash` before.  It caches automatically when we resolving user by username or fetching group members where user participates.

Is it possible to extract that info from TDLib's DB?

**Comment by Bannerets** [comment]
> Is it possible to extract that info from TDLib's DB?

It's not possible as far as I know.

See also https://github.com/tdlib/td/issues/212.

Anyway, you should open issue in [tdlib/td](https://github.com/tdlib/td/) if you want to get additional info.
