### ISSUE TITLE
Every time error: "Receive BOT_METHOD_INVALID for query 0xd4982db5"

### ISSUE THREAD

**Issue by Lord-FEAR** [Bannerets/tdl#28]
Everything works, but it writes this error every time it starts.
`[ 1][t 4][1539615657.389089584][netquery.cpp:54][!Session:2:main]       Receive BOT_METHOD_INVALID for query 0xd4982db5`

**Comment by Bannerets** [comment]
It's because tdlib sends a request for which bots have no rights. I think you should just ignore it.
Open issue in [tdlib/td](https://github.com/tdlib/td/) if you want to get additional info.
