### ISSUE TITLE
How to send code and pre text?

### ISSUE THREAD

**Issue by Lord-FEAR** [Bannerets/tdl#29]
`Formatted text to be sent; 1-GetOption("message_text_length_max") characters. Only Bold, Italic, Code, Pre, PreCode and TextUrl entities are allowed to be specified manually. `

Please write an example of sending a message with bold text, pre and code.

**Comment by Bannerets** [comment]
You can manually pass entities:

```js
  await client.invoke({
    _: 'sendMessage',
    chat_id: YOUR_CHAT_ID,
    input_message_content: {
      _: 'inputMessageText',
      text: {
        _: 'formattedText',
        text: 'bold italic code',
        entities: [
          { _: 'textEntity', offset: 0, length: 4, type: { _: 'textEntityTypeBold' } },
          { _: 'textEntity', offset: 5, length: 6, type: { _: 'textEntityTypeItalic' } },
          { _: 'textEntity', offset: 12, length: 4, type: { _: 'textEntityTypeCode' } }
        ]
      }
    }
  })
```

Or parse markdown / html string:

```js
// Markdown
  await client.invoke({
    _: 'sendMessage',
    chat_id: YOUR_CHAT_ID,
    input_message_content: {
      _: 'inputMessageText',
      text: client.execute({
        _: 'parseTextEntities',
        parse_mode: { _: 'textParseModeMarkdown' },
        text: '*bold* _italic_ `code`'
      })
    }
  })

// HTML
  await client.invoke({
    _: 'sendMessage',
    chat_id: YOUR_CHAT_ID,
    input_message_content: {
      _: 'inputMessageText',
      text: client.execute({
        _: 'parseTextEntities',
        parse_mode: { _: 'textParseModeHTML' },
        text: '<b>bold</b> <i>italic</i> <code>code</code>'
      })
    }
  })
```

See also:
- https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1send_message.html
- https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1formatted_text.html
- https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1text_entity.html
- https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_text_entity_type.html
- https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1parse_text_entities.html
