### ISSUE TITLE
Does not work in Electron on Windows

### ISSUE THREAD

**Issue by laptou** [Bannerets/tdl#32]
Despite my best efforts, I cannot get this to work in Electron. The program always fails and shows an error window indicating a C/C++ error, not even a JS error:

![image](https://user-images.githubusercontent.com/14832331/47576846-7aa46400-d913-11e8-9205-3055deb9fbb7.png)

### My steps:

1. Create an empty Node.js project.
2. Install `electron`, `tdl`, and `electron-rebuild`.
3. Run `npx electron-rebuild` to [retarget the native bindings to Electron](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md).
4. Download the precompiled Telegram binaries and put them in a `lib` folder.
5. Create index.js with the following code:

```
const { Client: TGClient } = require("tdl");

(async () => {
    console.log("initialising tg client");

    try {
        const tgClient = new TGClient({
            apiId: 000000,
            apiHash: "oops",
            binaryPath: "lib/tdjson",
            useTestDc: true,
            useMutableRename: true,
            verbosityLevel: 10
        });

        console.log("initialised tg client");

        await tgClient.connect();

        console.log("connected tg client");

        tgClient.on("update", (...args) => console.log("tg client: ", ...args));
        tgClient.on("error", (...args) => console.error("tg client: ", ...args));

    } catch (e) {
        console.error(e);
    }
})();
```

6. Run `npx electron .` to launch the program.
7. Program prints "initialised tg client", indicating that `tdl` successfully loads, but then crashes as soon as I call `connect()`.
7. Get confronted with this inscrutable error window.

**Comment by laptou** [comment]
Just tested, and it works for me too on Ubuntu 18.04 with exactly these steps. It is only failing on Windows, I'm going to test in a clean virtual machine to make sure this isn't an issue with my laptop.

**Comment by Bannerets** [comment]
Confirm that it fails on Windows.

---

It seems that it works with `ffi` instead of `ffi-napi`. Try this:

```
npm i https://github.com/node-ffi/node-ffi.git#169773db0d56c4c99225b307b3dc86a46f3af34d
npm i ref
npx electron-rebuild
```
then replace `require('ffi-napi')` with `require('ffi')` and `require('ref-napi')` with `require('ref')` in `node_modules/tdl/dist/tdlib-ffi.js` file.

---

After some debbuging I found that it crashes due to async ffi calls. Minimal reproducible example:

```js
const ffi = require('ffi-napi')
//const ref = require('ref-napi')
console.log(0)
const kernel32 = ffi.Library('kernel32', {
  Sleep: ['void', ['int32']]
})
console.log(1)
kernel32.Sleep.async(1000, err => console.log('err', err))
```

( `kernel32` here is just for example, you can use any function. Example from `tdl`: )

```js
const ffi = require('ffi-napi')
const tdjson = ffi.Library('tdjson', {
  'td_json_client_create': ['pointer', []]
})
tdjson.td_json_client_create.async((err, cl) => {
  if (err) console.log('Error', err)
  else console.log('Client created', cl)
})
```

I think we should open an issue somewhere in nodejs / electron / [node-ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi) repo.

**Comment by laptou** [comment]
Just wondering, what is the advantage of using ffi-napi instead of ffi? Just from looking over the repos, they seem to do exactly the same thing with exactly the same API.

**Comment by laptou** [comment]
Opened https://github.com/node-ffi-napi/node-ffi-napi/issues/20#issue-374667031.
