### ISSUE TITLE
Question about lib usage

### ISSUE THREAD

**Issue by allanberrocal** [Bannerets/tdl#36]
Hi @Bannerets just a question if you will.

When I run `npm install tdl` I get the following 

> npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "tdl" under a package
npm ERR! also called "tdl". Did you name your project the same
npm ERR! as the dependency you're installing?

I have already build TDLib. Do I need to link the binary of TDLib somewhere before I execute `npm install tdl` ? 

Thank you

**Comment by Bannerets** [comment]
> Did you name your project the same as the dependency you're installing?

---

You are executing `npm install tdl` in directory with package.json with field `"name": "tdl"`. You need to change your `package.json`.

**Comment by allanberrocal** [comment]
Thanks Sir, I figured my mistake and you confirmed it. Sorry about that.
