### ISSUE TITLE
Tdl by WebAssembly

### ISSUE THREAD

**Issue by AaronPorts** [Bannerets/tdl#39]
Can I use tdl and tdl-tdlib-wasm in browser by webassembly?

**Comment by Bannerets** [comment]
yes, you can use experimental `tdl@6.0.0-rc.2` (`$ npm install tdl@6.0.0-rc.2`) with `tdl-tdlib-wasm`. See https://github.com/Bannerets/tdl/tree/d44ea41454ba4b769f0ae9369bd014dc758c66a6/tdl-tdlib-wasm#readme for example.

You should compile tdlib to wasm manually, or you can use my prebuilt binary: https://github.com/Bannerets/tdlib-binaries#tdlib-130-release

**Comment by AaronPorts** [comment]
In your example Module() is td_wasm.js from tdlib-binaries? Cause when I try to use it or compile wasm file I've got next error:
![image](https://user-images.githubusercontent.com/32810520/51292889-80df4380-1a1d-11e9-9a68-252da24d8dde.png)
One more thing is that I have empty object after td_wasm.js import. So I replace 
```
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
```
with
`export default Module;`

**Comment by Bannerets** [comment]
If you load `td_wasm.js` in html: `<script src="td_wasm.js"></script>`, then `Module` should be in your global scope.

---

In your error `3c 21 44 4f` is the `<!DO` string. so, something is wrong, you are loading html file instead of wasm file.

**Comment by AaronPorts** [comment]
As I found @babel/plugin-transform-modules-commonjs should be used, if you want to import Module from td_wasm.js with babel 7, because babel dropped use of add-module-exports plugin on packages.
<hr></hr>
That was server issue with routing. Client requests /td_wasm.wasm file, but it receives html file with  response.

**Comment by Bannerets** [comment]
So now it works for you?

**Comment by AaronPorts** [comment]
Yes, authentication and api calls work just fine. One more question: can I save auth data in localstorage for its reuse?

**Comment by Bannerets** [comment]
I don't know, seems that official telegram web (https://github.com/evgeny-nadymov/telegram-react/) saves auth data. (it uses indexedDB). I guess tdlib v1.3.0 doesn't support it (`telegram-react` uses a newer private version of tdlib). You can try to to ask in https://github.com/tdlib/td issues.

**Comment by AaronPorts** [comment]
It turned out that user data can be saved by IDBFS (https://github.com/tdlib/td/issues/460#issuecomment-455519065)

**Comment by dfinityio** [comment]
@AaronPorts IDBFS example:
```
import { Client } from 'tdl'
import { TDLib } from 'tdl-tdlib-wasm'

var fs;

function createClient (options) {
  return new Promise(resolve => {
    Module().then(module => {
      const tdlib = new TDLib(module)

      // sync from persisted state into memory
      fs = module.FS
      fs.mkdir("/tdlib")
      fs.mount(fs.filesystems.IDBFS, {}, "/tdlib");
      fs.syncfs(true, err => {
        console.log(err)
        resolve(new Client(tdlib, options))
      })
    })
  })
}

// for testing
localStorage.debug = 'tdl:client'

async function main () {
  const client = await createClient({
    apiId: 2222, // Your api_id
    apiHash: 'YOUR_API_HASH', // Your api_hash
    useDefaultVerbosityLevel: true
  })
  
  console.log(client)
  
  await client.connectAndLogin(() => ({
    getPhoneNumber: retry => Promise.resolve(window.prompt(retry
      ? 'Invalid phone number, please re-enter:'
      : 'Please enter phone number:')),
    getAuthCode: retry => Promise.resolve(window.prompt(retry
      ? 'Wrong auth code, please re-enter:'
      : 'Please enter auth code:')),
    getPassword: (passwordHint, retry) => Promise.resolve(window.prompt(retry
      ? 'Wrong password, please re-enter:'
      : `Please enter password (${passwordHint}):`)),
    getName: () => {
      throw new Error('not supported')
    }
  }))
  
  const result = await client.invoke({
    _: 'getChats',
    offset_order: '9223372036854775807',
    offset_chat_id: 0,
    limit: 100
  })

  // latest 100 chats will be returned
  console.log('RESULT', result)

  // sync from memory state to persisted
  fs.syncfs(false, err => {
    console.log(err)
  })
}

main()
```

**Comment by MattNguyen** [comment]
@Bannerets - do you have any instructions for compiling tdlib to wasm? Was it straightforward using emscripten?

**Comment by Bannerets** [comment]
@MattNguyen See https://github.com/tdlib/td/issues/18, official TDLib instructions will come later
