### ISSUE TITLE
Destroy bad sqlite

### ISSUE THREAD

**Issue by mob2005** [Bannerets/tdl#40]
when  i use tdl it's show below error 
`[ 1][t 3][1549696839.615714312][TdDb.cpp:381][!Td]      Destroy bad sqlite db because of: [Error : 0 : [query:ATTACH DATABASE '/home/example/javascript/_td_database/db.sqlite.ecnrypted' AS encrypted KEY "x'06e1fbfd20d0755a4ff54e6b9bbffe27a4be52f0e11457a2b0130c0e6df95fee'"] failed: unable to open database: /home/example/javascript/_td_database/db.sqlite.ecnrypted]`

**Comment by Bannerets** [comment]
How to reproduce it?

Code to reproduce?

**Comment by mob2005** [comment]
put file downloaded from tdlib.native fix problem, another problem is when i call importContacts , it's always return :
`{ _: 'importedContacts', user_ids: [ 0 ], importer_count: [ 0 ] }`
my code : 
```
  const inputContacts = [
    {
      _: 'inputPhoneContact',
      client_id: '1',
      phone: '+xxxxxxxx',
      first_name: 'mob',
      last_name: 'mob'     
    }
  ]
  const importContact = await client.invoke({
    _: 'importContacts',
    contacts: inputContacts 
  })  
```
what's the correct way to call this function

**Comment by Bannerets** [comment]
`inputPhoneContact` is from another API, you should use `contact` instead - https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1contact.html.

```js
  const contacts = [
    {
      _: 'contact',
      phone_number: '+xxxxxxxx',
      first_name: 'mob',
      last_name: 'mob',
      vcard: '',
      user_id: 0
    }
  ]
  const importContact = await client.invoke({
    _: 'importContacts',
    contacts: inputContacts 
  })
```

Also see `importContact` reference: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1import_contacts.html
