### ISSUE TITLE
Failed to path auth

### ISSUE THREAD

**Issue by suhamera** [Bannerets/tdl#41]
I just started to deal with the tdl library and I have a lot of questions. Maybe I don't understand some conceptual things. I'm trying to use a [typical example](https://github.com/Bannerets/tdl/blob/master/examples/get-chats.js), but I have nothing. 

I can not pass authorization. As far as I understand, after I try to log in with client.login, I have to enter the "code", which TG sends in SMS or in the client, which I have already authorized. But in the examples there is no information on how I can enter this code for authorization to perform subsequent functions.

Moreover, having read the closed issues - I understand that certain objects have much more parameters. For example, when creating a client, [i can specify databaseDirectory](https://github.com/Bannerets/tdl/issues/9). Where can I read about the binding [TDLib](https://core.telegram.org/tdlib/getting-started) functions and this library?

**Comment by Bannerets** [comment]
By default `client.login(...)` asks you for code in CLI, you can override this behaviour.

> but I have nothing

It seems, that example doesn't contain `client.on('error', ...)` call, like [here](https://github.com/Bannerets/tdl/blob/56d9bd45c9438eba84c7653c5625fca60b79c34f/examples/handle-updates.js#L12). Without it errors can be silently ignored; ideally, you should always have a listener on `client.on('error')`. I'll add this line to the example.

Interface of `tdl` options is available [in readme](https://github.com/Bannerets/tdl/tree/develop#options).
TDLib parameters - https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1tdlib_parameters.html.

You can find documentation of all tdlib types and functions here -https://core.telegram.org/tdlib/docs/annotated.html (unfold `td_api` namespace).

Also, if something is working wrong, you can increase `verbosityLevel` param to get more logs:

```js
const client = new Client({
  // ...
  verbosityLevel: 5
})
```

**Comment by suhamera** [comment]
Thanx a lot, but I still have a problem with authorization.
So, I use this [example](https://github.com/Bannerets/tdl/blob/56d9bd45c9438eba84c7653c5625fca60b79c34f/examples/handle-updates.js#L12) and get something like this with verbose level = 5 runing with:

`node example.js`

I got
 
`
[ 3][t 4][1550280877.443006277][Td.cpp:4238][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}

[ 3][t 4][1550280877.448362827][Td.cpp:3308][!Td][&td_requests]	Receive request 1: setTdlibParameters {
  parameters = tdlibParameters {
    use_test_dc = false
    database_directory = "/usr/src/app/_td_database"
    files_directory = "/usr/src/app/_td_files"
    use_file_database = false
    use_chat_info_database = false
    use_message_database = true
    use_secret_chats = false
    api_id = 11***1
    api_hash = "edc*****a84dee394539*****7465581"
    system_language_code = "en"
    device_model = "tdlib"
    system_version = "node"
    application_version = "1.0"
    enable_storage_optimizer = true
    ignore_file_names = false
  }
}

[ 3][t 4][1550280877.448670864][Binlog.cpp:368][!Td]	Load: init encryption
[ 3][t 4][1550280877.448764563][Td.cpp:4238][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitEncryptionKey {
    is_encrypted = true
  }
}

... blah-blah-blah ...

Got update: {
  "_": "updateOption",
  "name": "supergroup_size_max",
  "value": {
    "_": "optionValueInteger",
    "value": 200000
  }
}
Got update: {
  "_": "updateOption",
  "name": "message_caption_length_max",
  "value": {
    "_": "optionValueInteger",
    "value": 1024
  }
}

Got update: {
  "_": "updateOption",
  "name": "t_me_url",
  "value": {
    "_": "optionValueString",
    "value": "https://t.me/"
  }
}
... blah-blah-blah ...

Please enter auth code: Got update: {
  "_": "updateConnectionState",
  "state": {
    **"_": "connectionStateConnecting"**
  }
}

Got update: {
  "_": "updateConnectionState",
  "state": {
    **"_": "connectionStateReady"**
  }
}

`
 but, there is no "asks you for code in CLI", how I can override this behaviour to paste my secret pin?

**Comment by Bannerets** [comment]
```
... blah-blah-blah ...

Please enter auth code: Got update: {
"_": "updateConnectionState",
"state": { **"_": "connectionStateConnecting"**
```

> Please enter auth code:

There is a query. However it quickly goes up because of much logging. After this line you can just enter the code and press Enter.

`client.login` funciton accepts this object:

```typescript
type LoginDetails = {
  type?: 'user',
  phoneNumber?: string,
  getAuthCode?: (retry?: boolean) => Promise<string>,
  getPassword?: (passwordHint: string, retry?: boolean) => Promise<string>,
  getName?: () => Promise<{ firstName: string, lastName?: string }>
} | {
  type: 'bot',
  token: string
}
```

You can pass `getAuthCode` function that returns promise:

```js
client.login({
  phoneNumber: '...',
  getAuthCode: async (retry) => {
    const code = await getPhoneCodeSomehow()
    return code
  }
})
```

Also you even can not use `client.login` fn and implement login process manually.

**Comment by suhamera** [comment]
Thanx a lot!
