### ISSUE TITLE
Error: Cannot read property 'sender_user_id' of undefined

### ISSUE THREAD

**Issue by suhamera** [Bannerets/tdl#42]
After start login with:
`
await client.connect()
  await client.login(() => ({
    phoneNumber: '79991111111' //my number
  }));
`

got error:
Got error: Error: Cannot read property 'sender_user_id' of undefined
    at Client._catchError (/usr/app/node_modules/tdl/dist/client.js:258:24)
    at Client._loop (/usr/app/node_modules/tdl/dist/client.js:280:14)
    at <anonymous>

**Comment by Bannerets** [comment]
That error seems to be in your user code, not in the given line of code, and not in the library.
Can you post fully reproducible example?

**Comment by suhamera** [comment]
Hm, I'll try to retry this error and share it.
