### ISSUE TITLE
Can't make it work after upgrade to ver. 6

### ISSUE THREAD

**Issue by denisakov** [Bannerets/tdl#44]
running this script with provided `ENV variables` (verified that they are available through the console.log):
```
const { TDL } = require('tdl-tdlib-addon')
const { Client } = require('tdl-tdlib-addon');

console.log('Creating a client for: \n'+process.env.PHONE_NUMBER);
console.log('Creating a client for: \n'+process.env.API_KEY);

new TDL('./node_modules/tdl-tdlib-addon/build/Release/td.node');

const client = new Client({
  apiId: process.env.API_KEY,
  apiHash: process.env.API_HASH,
})

async function main() {
  await client.connect()
  await client.login(() => ({
    phoneNumber: process.env.PHONE_NUMBER
  }))

  const result = await client.invoke({
    _: 'getChats',
    offset_order: '9223372036854775807',
    offset_chat_id: 0,
    limit: 100
  })

  // latest 100 chats will be returned
  console.log(result)
}

main()
```
fails with this:
/Users/jeff/tf_new/node_modules/tdl/dist/client.js:243
    if (!options.apiId) throw new TypeError('Valid api_id must be provided.');
                        ^

TypeError: Valid api_id must be provided.
    at new Client (/Users/jeff/tf_new/node_modules/tdl/dist/client.js:243:31)
    at Object.<anonymous> (/Users/jeff/tf_new/index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

Would appreciate the help.

**Comment by Bannerets** [comment]
See docs (and examples) in the [develop branch](https://github.com/Bannerets/tdl/tree/develop),
fixed your example:
```js
const { Client } = require('tdl')
const { TDLib } = require('tdl-tdlib-addon');

console.log('Creating a client for: \n'+process.env.PHONE_NUMBER);
console.log('Creating a client for: \n'+process.env.API_KEY);

const tdlib = new TDLib('./node_modules/tdl-tdlib-addon/build/Release/td.node');

const client = new Client(tdlib, {
  apiId: process.env.API_KEY,
  apiHash: process.env.API_HASH,
})

async function main() {
  await client.connect()
  await client.login(() => ({
    getPhoneNumber: async () => process.env.PHONE_NUMBER
  }))

  const result = await client.invoke({
    _: 'getChats',
    offset_order: '9223372036854775807',
    offset_chat_id: 0,
    limit: 100
  })

  // latest 100 chats will be returned
  console.log(result)
}

main()
```

**Comment by denisakov** [comment]
Was about to thank you and run the command tomorrow, but decided to check it quickly and:
```
const tdlib = new TDLib('./node_modules/tdl-tdlib-addon/build/Release/td.node');
              ^

TypeError: TDLib is not a constructor
```
So I do thank you for the fast reply! Any further ideas?)

**Comment by Bannerets** [comment]
It should work, can you past fully reproducible example?

**Comment by denisakov** [comment]
good question. I'm guessing the following should be enough:
package.json
```
{
  "name": "teleforward",
  "version": "0.0.1",
  "description": "The application will forward posts from telegarm groups to one single group",
  "main": "index.js",
  "scripts": {
    "test": "testtf"
  },
  "keywords": [
    "telegram"
  ],
  "author": "author",
  "license": "MIT",
  "homepage": "https://homepage",
  "dependencies": {
    "node-fetch": "^2.1.2",
    "request": "^2.85.0",
    "tdl": "^6.0.0-rc.2",
    "tdl-shared": "^0.7.0",
    "tdl-tdlib-addon": "^0.4.0",
    "uuid": "^3.2.1"
  }
}
```
index.js
```
const { Client } = require('tdl')
const { TDLib } = require('tdl-tdlib-addon');

console.log('Creating a client for: \n'+process.env.PHONE_NUMBER);
console.log('Creating a client for: \n'+process.env.API_KEY);

const tdlib = new TDLib('./node_modules/tdl-tdlib-addon/build/Release/td.node');

const client = new Client(tdlib, {
  apiId: process.env.API_KEY,
  apiHash: process.env.API_HASH,
})

async function main() {
  await client.connect()
  await client.login(() => ({
    getPhoneNumber: async () => process.env.PHONE_NUMBER
  }))

  const result = await client.invoke({
    _: 'getChats',
    offset_order: '9223372036854775807',
    offset_chat_id: 0,
    limit: 100
  })

  // latest 100 chats will be returned
  console.log(result)
}

main()
```

I don't really have anything else in this app.

**Comment by Bannerets** [comment]
Try `tdl-tdlib-addon@0.5.0`

**Comment by denisakov** [comment]
Hooray! Got it to work after the update. Had to change this line though:

`const tdlib = new TDLib('../build/Release/td.node');` as the long path didn't work.

The terminal went nuts... till I realized that I set verbosityLevel to 5 (don't do that kids).

So I'm getting the list of first 100 chat IDs now, which is awesome. It is slightly off-topic, but maybe you could direct me towards the solution for iterating through the whole list of chats (beyond the first 100)? The official docs on setting `offset_chat_id` and `offset_order` params, could not be more cryptic. Or maybe i'm slow.

**Comment by Bannerets** [comment]
Long time ago I wrote something similar, I'll just give it to you:

```js
const FIRST_CHAT = Object.freeze({ order: '9223372036854775807', id: 0 })

export const getAllChats = async (client: TdlClient): Promise<Td$chat[]> => {
  let chats = []

  while (true) {
    const chat = chats[chats.length - 1] ?? FIRST_CHAT

    const newChats = await client.invoke({
      _: 'getChats',
      offset_order: chat.order,
      offset_chat_id: chat.id,
      limit: 100
    }).catch(console.error) ?? { chat_ids: [] }

    const newChatIds = newChats.chat_ids

    if (newChatIds.length === 0) break

    const chatPromises = newChatIds.map(chatId =>
      client.invoke({
        _: 'getChat',
        chat_id: chatId
      }))

    chats = chats.concat(await Promise.all(chatPromises))
  }

  return chats
}
```

You can remove `getChat` requests if you want only ids.

**Comment by denisakov** [comment]
Got it to work! Thank you so much!
