### ISSUE TITLE
Convenience methods

### ISSUE THREAD

**Issue by YouTwitFace** [Bannerets/tdl#46]
Can you add convenience methods? (e.g. `client.sendMessage()`, ...)

**Comment by Bannerets** [comment]
As I said in #19, I have no plans to add helpers in this library.

If you're talking about adding a autogenerated method for each TDLib function, like here in your commit https://github.com/YouTwitFace/tdl/commit/217d932f17b29a6a29e60160e7d012cab14ec820#diff-cf27c1d543e886c89cd9ac8b8aeaf05bR536, then there is no much point in it (unless you're using plain JS, but the library is focused to work with TypeScript/Flow), it won't be added. Also it will require regeneration on each minor tdlib update; currently only typings need to regenerate.

**Comment by YouTwitFace** [comment]
Okay.
