### ISSUE TITLE
Any need for wasm tdlib instance?

### ISSUE THREAD

**Issue by mnb3000** [Bannerets/tdl#47]
Today Telegram team released official wasm wrapper for tdlib called [tdweb](https://www.npmjs.com/package/tdweb)
Is there any need to maintain wasm tdlib instance?

**Comment by Bannerets** [comment]
It makes less sense now, but I won't remove it, maintenance costs aren't high.
Wasm and node.js wrappers in this library have the same interface, so you can easily replace one with another.

Also, I'll perhaps release tdl v6.0.0 with tdlib v1.4.0 support tomorrow (UTC), after the 1.4.0 tag will be added to the tdlib repo.

**Comment by mnb3000** [comment]
Thank you, waiting for tdlib 1.4 tag :)
