### ISSUE TITLE
 [Question] How to logout/destroy session of user

### ISSUE THREAD

**Issue by egarciahz** [Bannerets/tdl#50]
This is more a question than a problem, 

I want to close / destroy the user session but I do not understand how to access the tdlib library method or how to access the user id. I'm using the 'destroy' tdl method but I think it's not right

**Comment by Bannerets** [comment]
Does [logOut](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1log_out.html) tdlib method work for you?

```js
client.invoke({ _: 'logOut' })
```
