### ISSUE TITLE
Send sticker doesn't work for bot client

### ISSUE THREAD

**Issue by ramesh333** [Bannerets/tdl#52]
I wanted to send stciker using file_id
BotClient.invoke({
    '_': "sendSticker",
    chat_id: user_id, // channel public id -10089282912
    sticker: sticker_id, //file id "CAADBAADlAMAAu7HTghzD5rxxzAtAwI"
    disable_notification: false,
    })

Promise never resolves and is always in ending state
I have written above code based on https://core.telegram.org/bots/api#stickerset

**Comment by Bannerets** [comment]
https://core.telegram.org/bots/api is for Bot API. You should use methods from https://core.telegram.org/tdlib/docs/annotated.html. Specifically, you need to call the [`sendMessage`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1send_message.html) method with the `input_message_content` field set to [`inputMessageSticker`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_message_sticker.html) object.

If `verbosityLevel` is set to 1 or above, you should see an error in the console.

**Comment by ramesh333** [comment]
Thanks for the right guidance, In my case I should send a stikcer based on its file_id, but unfortunately when I send via inputField it says cannot parse to int .
  BotClient.invoke({
    '_': "sendMessage",
    chat_id: user_id,
    disable_notification: false,
    from_background: true,
    input_message_content: {
      '_': "inputMessageSticker",
      sticker: {
        '_': "inputFileId",
        id: sticker_id //file id "CAADBAADlAMAAu7HTghzD5rxxzAtAwI"
      }
      }
  }


Could you please give sample sample code to send sticker by file_id
I'm confused what to choose here for file_id  (inputFileGenerated, inputFileId, inputFileLocal, and inputFileRemote.)
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_input_file.html

**Comment by Bannerets** [comment]
I guess you should use [`inputFileRemote`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_remote.html) with `id` set to your file_id.

**Comment by ramesh333** [comment]
This finally works.... Thanks
