### ISSUE TITLE
Question about Module(). in the createClient function 

### ISSUE THREAD

**Issue by telion2** [Bannerets/tdl#55]
Hi, 
I just started trying out your package. 
The documentation tells me to use this 
`function createClient (options) {
  return new Promise(resolve => {
    Module().then(module => {
      const tdlib = new TDLib(module)
      resolve(new Client(tdlib, options))
    })
  })
}`
to create a client. However Module().then(... is unresolved. 
Do I need the npm package "module" (https://www.npmjs.com/package/module) for it to work? 
If so I guess a update of the readme would be useful?

**Comment by telion2** [comment]
Ah and its about the wasm (tdl-tdlib-wasm) package.

**Comment by Bannerets** [comment]
`Module` is from tdlib compiled via emscripten. You can import it using ES6modules/CJS or via the `<script>` tag in HTML.

For example, see the js file in [this archive](https://github.com/Bannerets/tdlib-binaries/blob/675e3d93e8f62318795dfef4f2991300bdfd974f/1.3.0/emscripten/td_wasm.zip).

**Comment by telion2** [comment]
Sorry but I'm still a bit confused. My context would be to use tdlib in angular, so basically in a browser. 
For this I thought I use tdl-tdlib-wasm to add tdlib to the browser. After I have read some other issues about tdlib binarys I got lost on how the whole thing is supposed to work. 
So the way I understand it, is that I need the tdlib binary like this one: https://github.com/ForNeVeR/tdlib.native/releases
But how do I handle that binary exactly? Is Module part of it, or do I need to import it speratly? 
Do I just do `import * as Module from 'path-to-td-binary';` ?
or:  `import * as Module from 'path-to-js-file-you-mentioned(td_wasm.js)';` ? 
I mean if the binary is required, how does tdl or tdl-tdlib-wasm know where it is?

**Comment by Bannerets** [comment]
https://github.com/ForNeVeR/tdlib.native/releases doesn't have binaries for wasm. You can compile it yourself ([instructions](https://github.com/tdlib/td/tree/1a3d31949e0fe8923206aeff85f2fd24787c9603/example/web)). In the end you'll get files like in [this archive](https://github.com/Bannerets/tdlib-binaries/blob/675e3d93e8f62318795dfef4f2991300bdfd974f/1.3.0/emscripten/td_wasm.zip) (though this one is for outdated tdlib 1.3.0, so I don't recommend using it). The js file in the archive exports Module.

> or: import * as Module from 'path-to-js-file-you-mentioned(td_wasm.js)'; ?

Yes, like this. Or maybe `import { Module } from 'path-to-js-file-you-mentioned(td_wasm.js)'`, I don't remember. See the contents of compiled js file to determine what exactly you need to import.

---

You can also just use the official [tdweb](https://www.npmjs.com/package/tdweb) package. It contains prebuilt TDLib binaries.

**Comment by telion2** [comment]
Oh wow, thank you for your fast response. 
I probably will just try both tdweb and this package. I saw tdweb earlier, but it had quite short documentation, so I was confused on how to use it. 
Thanks a lot.^^

**Comment by Sparkenstein** [comment]
Hey @Bannerets 
I think I am having the same Issue, I am trying to run tdl-wasm module, but I don't clearly understand Is `tdl-tdlib-wasm` not a complete wrapper around tdlib? for using `tdl-tdlib-wasm` do I have to import `tdweb` as well? I mean the wasm file from tdweb. othewise where to get this `td_wasm.js` file? 

PS: is tdl-tdlib-wasm still in experiemental phase? I was thinking of using it

**Comment by Bannerets** [comment]
@Sparkenstein `tdweb` is not needed. To get `td_wasm.js` you need to compile TDLib using emscripten ([script example](https://github.com/tdlib/td/blob/v1.6.0/example/web/build-tdlib.sh)). Also, aside of the `td_wasm.js` file, there should be the `td_wasm.wasm` binary file.

Though, you'd better use official `tdweb`, it's a more high-level wrapper and should be more convenient to use. It also contains prebuilt `td_wasm`.
`tdl-tdlib-wasm` was created before `tdweb` existed.

> PS: is tdl-tdlib-wasm still in experiemental phase? I was thinking of using it

Its development was paused due to the `tdweb` release.
