### ISSUE TITLE
Questions about the methods

### ISSUE THREAD

**Issue by DestroyerIV** [Bannerets/tdl#58]
Hi. I try to recover the number of chats where I am, I cannot recover it. I have tried asynchronously and synchronously. None of them offers results because by doing so synchronously, it shows me the following message in the console:

`Promise {<pending>}`

How could I deliver that promise?

The code I play with is this:

```js
function gettingChats(){
        const chats = api.client.invoke({
                _: 'getChats',
                offset_order: '9223372036854775807',
                offset_chat_id: 0,
                limit: 100
        });
        console.log(chats)
};

gettingChats()
```
The update handler works perfectly, but this particular method does not.

Thanks in advance

**Comment by Bannerets** [comment]
The `invoke` functions returns a [ES6 promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), you need to wait until it is fulfilled either via `.then` or async/await.

```js
async function gettingChats(){
        const chats = await api.client.invoke({
                _: 'getChats',
                offset_order: '9223372036854775807',
                offset_chat_id: 0,
                limit: 100
        });
        console.log(chats)
};

gettingChats()
```

```js
function gettingChats(){
        api.client.invoke({
                _: 'getChats',
                offset_order: '9223372036854775807',
                offset_chat_id: 0,
                limit: 100
        }).then(chats => console.log(chats))
};

gettingChats()
```

**Comment by IscoV** [comment]
When I try to use this method, I get this error:
```
{
  _: 'error',
  code: 400,
  message: 'Initialization parameters are needed: call setTdlibParameters first'
}
```

I have tried every possible way to set the TDLib parameters but without success.

Thanks for advance
