### ISSUE TITLE
New Error Dynamic Linking

### ISSUE THREAD

**Issue by DestroyerIV** [Bannerets/tdl#61]
Hello again, when trying to set the TDLib instance and its respective file (tdlibjson.so)

I am trying to set the credentials on a Raspberry Pi 3B +
I have openSSL version 1.1.1d and version of npm 6.11.3 and version of nodejs 10.17.0
The structure where the files are located is as follows:
```
- index.js
- tdlibjson.so
- tdlibjson.so.1.5.1
```
it shows me the following error:
```

var { Client } = require('tdl');
var { TDLib } = require('tdl-tdlib-ffi');
var lib = './libtdjson.so';
var tdlib = new TDLib(lib)

In console

Error: Dynamic Linking Error: ./libtdjson.so: undefined symbol: __atomic_fetch_add_8

```

All help is appreciated

**Comment by Bannerets** [comment]
Doesn't that answer help you? https://github.com/tdlib/td/issues/646#issuecomment-517077970

Also, did you compile the binary on the same device? Which version of TDLib do you use?

**Comment by DestroyerIV** [comment]
Yes, compile it and try to use it on the same device

I'll try the answer

**Comment by DestroyerIV** [comment]
The error is not when compiling. I can't start the script since as I run it, it shows me that error

**Comment by Bannerets** [comment]
Sure, I understand that.

**Comment by DestroyerIV** [comment]
> 
> 
> Doesn't that answer help you? [tdlib/td#646 (comment)](https://github.com/tdlib/td/issues/646#issuecomment-517077970) (`Add link_libraries(atomic) to the top-level CMakeLists.txt at line 5`)
> 
> Also, did you compile the binary on the same device?

I already made the change he suggested but it didn't work either

**Comment by DestroyerIV** [comment]
@Bannerets Any solution or some other idea?

**Comment by Bannerets** [comment]
I may try it in the qemu virtual machine a little bit later

**Comment by DestroyerIV** [comment]
@Bannerets Any advance? Thanks in advance

**Comment by Bannerets** [comment]
@DestroyerIV There are many complications with running raspbian inside qemu (e.g. `raspbi3` machine doesn't support network). The real raspberry pi will be available for me only after ~6 days.

Aside of that, could you show the output of `ldd libtdjson.so`?

**Comment by DestroyerIV** [comment]
> @DestroyerIV Hay muchas complicaciones con la ejecución de raspbian dentro de qemu (por ejemplo, la `raspi3`máquina no es compatible con la red). La verdadera frambuesa pi estará disponible para mí solo después de ~ 6 días.
> 
> Aparte de eso, ¿podría mostrar la salida de `ldd libtdjson.so`?

Your suggestion returns this:
`destroyer@raspberrypi:~/tdlib/td/build $ ldd libtdjson.so                               linux-vdso.so.1 (0x7ed30000)                                               /usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x7627e000)                                   libssl.so.1.1 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.1 (0x761ff000)                                                                              libcrypto.so.1.1 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1 (0x75fee000)                                                                        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x75fdb000)             libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x75fb0000)               libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x75e69000)                                                                            libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x75de7000)               libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x75dba000)                                                                                  libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x75d90000)                                                                              libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x75c42000)               /lib/ld-linux-armhf.so.3 (0x76fc8000)`

**Comment by DestroyerIV** [comment]
I forgot to comment that version 1.4.0 worked perfectly on the same device

**Comment by DestroyerIV** [comment]
@Bannerets Some news? Thanks in advance

**Comment by Bannerets** [comment]
@DestroyerIV Sorry for the delay. I've got only Raspberry Pi 3 Model B with Raspbian 8.0 jessie, TDLib v1.5.0 compiles successfully (via g++) and works correctly for me. I, though, didn't test with clang.
Did you compile via clang or g++?

**Comment by DestroyerIV** [comment]
> @DestroyerIV Sorry for the delay. I've got only Raspberry Pi 3 Model B Rev 1.2 with Raspbian 8.0 jessie. TDLib v1.5.0 compiles successfully (via g++) and works correctly for me, I didn't need to add `libatomic` linking to cmakelists. I, though, didn't test with clang.
> Did you compile via clang or g++?

I use Clang since raspberry pi b3 + doesn't have more than 1GB of ram

**Comment by DestroyerIV** [comment]
Do you compile it with g ++? How long is the compilation process?

**Comment by Bannerets** [comment]
I also have 1GB of ram. I compiled it via g++ with the `php SplitSource.php` method (https://github.com/tdlib/td#building), it worked. Compilation was something like 4-6 hours. My microSD is very slow, though.

**Comment by DestroyerIV** [comment]
let's see, I think I didn't explain myself ... the compilation is done correctly, what I don't get is to find the `tdlibjson.so` file when creating the client showing the error that I indicated above

**Comment by Bannerets** [comment]
Yes, i understand it. I'm saying that for me it works out of the box (I can use the library and can create a client without errors), while I compiled it via g++ (didn't test with clang).
