### ISSUE TITLE
How can i registered user ?

### ISSUE THREAD

**Issue by zababurinsv** [Bannerets/tdl#64]
Hi.

In your readme file i looking this example

// Example
await client.login(() => ({
  getPhoneNumber: retry => retry
    ? Promise.reject('Invalid phone number')
    : Promise.resolve('+9996620001'),
  getAuthCode: retry => retry
    ? Promise.reject('Invalid auth code')
    : Promise.resolve('22222'),
  getPassword: (passwordHint, retry) => retry
    ? Promise.reject('Invalid password')
    : Promise.resolve('abcdef'),
  getName: () =>
    Promise.resolve({ firstName: 'John', lastName: 'Doe' })
}))

But i can not used this code.

I can set phone number but then my number is true, on my telegram i get auth code.
I can sending this auth code on mying server, but how can i wait his, using this code ?
Can you write exampe with await function ?
and if i have not authtorisation in telegram. How send auth on my phone ?

Example: (Node js - express)

app.post('/auth', async (req, res) => {

req['body']['authCode] - ???

await client.login(() => ({
  getPhoneNumber: retry => retry
    ? Promise.reject('Invalid phone number')
    : Promise.resolve(req['body']['phoneNumber']),
  getAuthCode: retry => retry
    ? Promise.reject('Invalid auth code')~~~~>> " can i set creating function in this place ? "
    : Promise.resolve('22222'), - HOW ?
  getPassword: (passwordHint, retry) => retry
    ? Promise.reject('Invalid password')
    : Promise.resolve('abcdef'),
  getName: () =>
    Promise.resolve({ firstName: 'John', lastName: 'Doe' })
}))

})

**Comment by banghasan** [comment]
Hi, why close? is this solved?

what a solution?
