### ISSUE TITLE
Failed to parse JSON object as TDLib request: Unknown class "RegisterUser"

### ISSUE THREAD

**Issue by zababurinsv** [Bannerets/tdl#65]
Hi.
I want registre user.
I found in documentation this class

registerUser Class Referencefinal
Inherits Function

state:
authorizationStateWaitRegistration

But when i want to use this class i get this error.
Failed to parse JSON object as TDLib request: Unknown class "RegisterUser".

in what does i  wrong ? Or how can i  register new user ?

**Comment by Bannerets** [comment]
@zababurinsv use `registerUser` instead of `RegisterUser`

**Comment by zababurinsv** [comment]
I 3 days ago spent an 3 hours for this )
