### ISSUE TITLE
client.connect() failed

### ISSUE THREAD

**Issue by zababurinsv** [Bannerets/tdl#67]
Hi.
it is log file.

[ 2][t 4][1574887238.631773949][TdDb.cpp:313][#1][!Td]	Got PRAGMA user_version = 9
[ 2][t 4][1574887238.632516146][AuthDataShared.cpp:112][#1][!Td]	DcId{1} [auth_key_id:0][state:Empty]
[ 2][t 4][1574887238.633050919][SessionMultiProxy.cpp:121][#1][!SessionMultiProxy:1:main]	[session_count:1]
[ 2][t 4][1574887238.633115053][Session.cpp:144][#1][!SessionProxy:1:main]	Generate new session_id 6974633098333251877 for auth key 0 for DC1
[ 2][t 3][1574887248.645066023][Session.cpp:1133][#1][!Session:1:main::HandshakeActor]	Failed to open connection: [Error : 0 : Timeout expired : [149.154.175.50:443] to DcId{1} from [192.168.100.9:46284]]
[ 2][t 4][1574887248.645218134][Session.cpp:1066][#1][!Session:1:main]	Handshake is not yet ready
[ 2][t 4][1574887248.795817137][Session.cpp:144][#1][!GetConfigActor]	Generate new session_id 1405813238098632749 for temp auth key 0 for DC4
[ 2][t 4][1574887251.868845224][ConnectionCreator.cpp:879][#1][!ConnectionCreator]	[[2001:b28:f23d:f001::a]:443] to DcId{1}: [PosixError : Network is unreachable : 101 : Failed to connect to [[2001:b28:f23d:f001::a]:443]]
[ 2][t 4][1574887255.868880987][ConnectionCreator.cpp:879][#1][!ConnectionCreator]	[[2001:b28:f23d:f001::a]:80] to DcId{1}: [PosixError : Network is unreachable : 101 : Failed to connect to [[2001:b28:f23d:f001::a]:80]]

What is the PosixError ? And how can i get session_id in tdl ?

**Comment by Bannerets** [comment]
Your network interface is down, you don't have connection to the Internet.

> And how can i get session_id in tdl ?

You shouldn't. That's internal MTProto stuff, TDLib doesn't have public API to get the session id.

**Comment by zababurinsv** [comment]
thanks.
