### ISSUE TITLE
file upload sample

### ISSUE THREAD

**Issue by Exlord** [Bannerets/tdl#75]
Hi, could you provide a file upload , file send and file resend by id samples ?? 

And send file by url !

Tnx

**Comment by thekeithwaters** [comment]
Hi there.  Thanks so much for this - it was very easy to implement.

I've got basic functionality working, but I would really appreciate some **sample code for sending & receiving a file / picture,**  PLEASE ?

Thanks in advance

**Comment by smff** [comment]
any updated?

**Comment by Bannerets** [comment]
There are some examples in #129. If you have questions on how to use TDLib, ask in the tdlib telegram chat or open new issues.
