### ISSUE TITLE
How to use with many bots

### ISSUE THREAD

**Issue by Exlord** [Bannerets/tdl#76]
Hi, I have bot management system with nodejs, I want to use this lib to increase file upload/download limit for my bots ...

I saw the multi account example but there is warning in the comments ...

So practically how many clients can I create ? whats the best way to use this with 1000+ bots?

**Comment by Bannerets** [comment]
> whats the best way to use this with 1000+ bots?

The best way would be to write a node.js addon in C++ that uses the TDLib's [ClientActor](https://core.telegram.org/tdlib/docs/classtd_1_1_client_actor.html) API directly.

**Comment by Exlord** [comment]
> 
> 
> > whats the best way to use this with 1000+ bots?
> 
> The best way would be to write a node.js addon in C++ that uses the TDLib's [ClientActor](https://core.telegram.org/tdlib/docs/classtd_1_1_client_actor.html) API directly.

don't really khow much c++, 
can I create like 5 clients and keep them connected but login/logout with each one whenever needed?

**Comment by Loskir** [comment]
You can create a new client when you need to login and destroy it when you need to logout

**Comment by Exlord** [comment]
> 
> 
> You can create a new client when you need to login and destroy it when you need to logout

Is that ok? for performance ?? Isn't creating a new client heavy on load and resources?

**Comment by Loskir** [comment]
tdlib is already heavy by itself, it takes ~3 seconds for a client to be created.
so it may be not ok to create a large amount of clients.
