### ISSUE TITLE
Simple http redirect instead of proxy 

### ISSUE THREAD

**Issue by Exlord** [Bannerets/tdl#77]
I am from Iran and telegram servers are blocked here, so for my bot server I have simple shared host in Europe that does a simple url redirect to api.telegram.org ....

I saw the proxy example but it uses mtproto proxy ... is there anyway I can change the server ip/urls to my proxy host and do a redirect from there?

**Comment by Bannerets** [comment]
You mean, you use a reverse proxy (and not http redirects via the `Location` header)?

**Comment by Exlord** [comment]
> 
> 
> You mean, you use a reverse proxy (and not http redirects via the `Location` header)?

I want to keep the cost down so I tried it with a shared host, directadmin has a section called 'site redirection', I think it creates a rewrite rule in apache ...

But I have tested this with nginx reverse proxy too, it works as well ...
