### ISSUE TITLE
Channel data gathering

### ISSUE THREAD

**Issue by skakodube** [Bannerets/tdl#78]
So, I need to gather some general statistics and the amount of members from a channel by its URL(or sth similar), being not an admin of it. Is it possible to manage this with your library? 
I've read the whole documentation and I could't find anything similar to what I'm taking about and what I've found in original telegram API :

- https://core.telegram.org/method/messages.getStatsURL 
- https://core.telegram.org/method/channels.getParticipants

If it is, could you give me any hints how can I achieve this?

**Comment by Bannerets** [comment]
That isn't the right documentation. See the TDLib API here: https://core.telegram.org/tdlib/docs/annotated.html.

There's a similar to `messages.getStatsURL` method: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_statistics_url.html. Though, it is for working with `tg://statsrefresh` links, so maybe that's not what you are looking for.

You can get the amount of members from a `supergroupFullInfo` object: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1supergroup_full_info.html

**Comment by skakodube** [comment]
Thank you for answering!

But my question was rather: Can I fetch the data from a channel by it's URL, when I'm NOT an admin or member? I'm building a web service for telegram adverts and I need to process channel data to register them in my app. Or should I use the bot-API for this? How do you think?
