### ISSUE TITLE
Client.connect ends the process immediately

### ISSUE THREAD

**Issue by Zoha** [Bannerets/tdl#79]
Hi.
I installed package as the readme file explained 
First I faced this error :
https://github.com/Bannerets/tdl/issues/25
After copying given file in the root of project error is gone but now problem is app not working 
When I call `client.connect` process ends without any error 
If I dont call this method other methods still not working (with no error) but process will stay alive 

I also read  [This](https://steemit.com/node/@cryptosharon/how-to-install-tdl-javascript-tool-for-telegram-userbots-and-clients)  article and did every thing that our friend said but result is the same!
Can you help?

**Comment by jsProj** [comment]
How did you fix this?

**Comment by Zoha** [comment]
Problem was building tdlib in windows 
I build tdlib compeletly and then  copied build files into root of project 
And then it works. 
Note : after building in windows files wil be in build/release
