### ISSUE TITLE
I can't install tdl-tdlib-ffi

### ISSUE THREAD

**Issue by ghost** [Bannerets/tdl#81]
![photo_2020-05-26_20-25-12](https://user-images.githubusercontent.com/58949392/82919244-349c0000-9f8f-11ea-98c9-28ec6ef0d4e4.jpg)
![photo_2020-05-26_20-25-15](https://user-images.githubusercontent.com/58949392/82919257-3960b400-9f8f-11ea-9b1f-aa23d74536f3.jpg)

**Comment by Bannerets** [comment]
Try to compile via clang (install clang and set `CC` to `/usr/bin/clang`, `CXX` to `/usr/bin/clang++`)

**Comment by NMIFUN** [comment]
I installed tdlib via clang

**Comment by Bannerets** [comment]
I mean `libffi`, not tdlib. Just set the `CC` and `CXX` env variables before executing the npm install.
