### ISSUE TITLE
Conflict in the Electron.js environment

### ISSUE THREAD

**Issue by Newserver-dev** [Bannerets/tdl#84]
I ran into a situation when the library connection string inside the electron application breaks the connection with the developer's tool and breaks the entire application. If included in the main index js file, the application will not even start. But if you don't use electron and just run it through node.js, everything works and you can work with it.
`const { TDLib } = require('tdl-tdlib-ffi')` crash my app.  OS windows 8. node 12.18.3. npm 6.14.6
Installing package in app
  ```
"dependencies": {
    "adm-zip": "^0.4.13",
    "appdata-path": "^1.0.0",
    "async": "^3.1.0",
    "async-require": "^1.2.2",
    "discord-rpc": "3.1.0",
    "ejs": "^2.7.1",
    "ejs-electron": "^2.0.3",
    "electron-root-path": "^1.0.16",
    "electron-updater": "^4.1.2",
    "ffi-napi": "^3.0.1",
    "fs-extra": "^8.1.0",
    "github-syntax-dark": "^0.5.0",
    "http-proxy": "^1.18.1",
    "jquery": "^3.5.1",
    "node-stream-zip": "^1.11.2",
    "request": "^2.88.0",
    "semver": "^6.3.0",
    "sha1-file": "^2.0.0",
    "tar-fs": "^2.0.0",
    "tdl": "^6.1.0",
    "tdl-tdlib-ffi": "^2.0.0",
    "tglib": "^3.0.5",
    "unzip": "^0.1.11",
    "winreg": "^1.2.4",
    "zlib": "^1.0.5"
  },
```
What can conflict? I want to use this library for registration purpose

**Comment by Bestulo** [comment]
Did you solve your problem

**Comment by Newserver-dev** [comment]
> Did you solve your problem
yes. Node js local and globals were different. The global was new, but inside the app it was old
