### ISSUE TITLE
setLogStream Class

### ISSUE THREAD

**Issue by seiya-git** [Bannerets/tdl#85]
Hello. How to set setLogStream for verbose logs?
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_log_stream.html

**Comment by Bannerets** [comment]
Hi. `setLogStream` only sets the log stream for logging (you can output the logs to a file), not verbosity level. To get verbose logs you can use [setLogVerbosityLevel](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_log_verbosity_level.html), call it like any other method:

```js
client.execute({
  _: 'setLogVerbosityLevel',
  new_verbosity_level: 5
})
```

`tdl` also has a wrapper over it, you can pass the `verbosityLevel` option to the `Client` constructor:

```js
new Client(..., {
  ...
  verbosityLevel: 5
})
```

**Comment by Bannerets** [comment]
```js
client.execute({
  _: 'setLogStream',
  log_stream: {
    _: 'logStreamFile',
    path: 'file.txt',
    max_file_size: 10485760
  }
})
