### ISSUE TITLE
errror: this._tdlib.execute is not a function

### ISSUE THREAD

**Issue by MoJongleur** [Bannerets/tdl#87]
I'm trying to use the code from the example, but I get the following error:
"(node:2936) UnhandledPromiseRejectionWarning: Error while creating client: TypeError: this._tdlib.execute is not a function"

What do i do?

```
const client1 = new Client(TDLib, {
  apiId: 'some id',
  apiHash: 'some hash',
  databaseDirectory: '_td_database',
  filesDirectory: '_td_files'
})

client2.on('error', e => console.error('Client1 error', e))

async function main() {
  await Promise.all([ client1.connect() ])

  await client2.login()

}

main()
```

**Comment by Bannerets** [comment]
How's `TDLib` defined?

**Comment by MoJongleur** [comment]
> How's `TDLib` defined?
> 
> See the readme for an example of how `TDLib` should be defined

const { Client } = require('tdl');
const { TDLib } = require('tdl-tdlib-ffi');

**Comment by Bannerets** [comment]
```diff
- const client1 = new Client(TDLib, {
+ const client1 = new Client(new TDLib(), {
```

**Comment by MoJongleur** [comment]
> ```diff
> - const client1 = new Client(TDLib, {
> + const client1 = new Client(new TDLib(), {
> ```

Yes, it works. Thank you so much)
