### ISSUE TITLE
Can't lock file "td.binlog"

### ISSUE THREAD

**Issue by luksireiku** [Bannerets/tdl#90]
I'm getting this error, it's there any way to close it or I am missing something?

`Can't lock file "/usr/src/app/.tdlib_files/polaris/database/td.binlog", because it is already in use; check for another program instance running`

**Comment by Bannerets** [comment]
It seems you created multiple clients with the same database.

Check which processes are using the database file (`lsof | grep td.binlog`) and can kill them.
