### ISSUE TITLE
Get tdlib error response

### ISSUE THREAD

**Issue by luksireiku** [Bannerets/tdl#92]
It's there any way to get the error response json instead of the exception name?
Example of another tdlib implementation: `{'@type': 'error', 'code': 400, 'message': 'INVITE_HASH_INVALID', '@extra': {'request_id': 'ebd41a6d2476470289b734c6b63d322d'}}`

**Comment by Bannerets** [comment]
What do you mean?

The promise rejects with an object like that, e.g.
```js
client.invoke({ ... })
  .then(
    result => { ... },
    error => console.error(error) // {_: 'error', code: 400, message: 'INVITE_HASH_INVALID'}
  )

**Comment by luksireiku** [comment]
Then I'm just an idiot, I was using the .message like with exceptions and I didn't know I was receiving everything.
