### ISSUE TITLE
file_id param from getFile method must be a String

### ISSUE THREAD

**Issue by jantocv** [Bannerets/tdl#93]
### Expected Behavior

Get a file by using `getFile` method providing `file_id` and `file_type` (if it is known).

### Actual Behavior

Error happens because `file_id` should be a `string` but a `number` is expected by the library type definition of the `getFile` method can be seen here:

https://github.com/Bannerets/tdl/blob/533384d3ca57d5fb17a87bf9193f077cfe2fcca9/packages/tdl/types/tdlib.d.ts#L16294

Reading in the documentation of the Telegram API a `string` type for `file_id` is expected:
https://core.telegram.org/bots/api#getfile

### Steps to reproduce the Behavior

1 - Given the photo properties from a certain message:

```
{
        "_":"photoSize",
        "type":"x",
        "photo":{
            "_":"file",
            "id":2,
            "size": ...,
            "expected_size": ...,
            "local": {
                ...
            },
            "remote": {
                "_":"remoteFile",
                "id":"THIS-IS-YOUR-FILE-ID",
                "unique_id":"...",
                "is_uploading_active": ...,
                "is_uploading_completed": ...,
                "uploaded_size": ...
            }
        },
        ...
    },
```

2 - Invoke `getFile` using `photo.remote.id` as the `file_id`.
3 - Error example:

``` 
{"_":"error","code":400,"message":"Failed to parse JSON object as TDLib request: Can't parse \"THIS-IS-YOUR-FILE-ID\" as number"}
```

**Comment by Bannerets** [comment]
https://core.telegram.org/bots/api is a different API. See TDLib API reference here: https://core.telegram.org/tdlib/docs/annotated.html. E.g. getFile: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_file.html. You can also browse the td_api.tl file: https://github.com/tdlib/td/blob/v1.6.0/td/generate/scheme/td_api.tl#L3162.
So, `getFile` accepts a number in TDLib.

I think `getFile` should be used with `photo.id`, not `photo.remote.id`. For remote ids there's [`getRemoteFile`](https://github.com/tdlib/td/blob/v1.6.0/td/generate/scheme/td_api.tl#L3167) that accepts a string.
