### ISSUE TITLE
What's the best way to forward a message received?

### ISSUE THREAD

**Issue by GuilhermeAmado** [Bannerets/tdl#99]
I tried: 
`client.invoke({
    _: 'forwardMessages',
    chat_id: chat.id,
    from_chat_id: incoming_chat.id,
    message_ids: [msg.id],
});`

But it didn't work.
Can i get a full received message object and use with the sendMessage method?

**Comment by Bannerets** [comment]
> But it didn't work.

It should work, what was the error? Note that  in `message_ids` you probably should use the id you received from the updates, not a temporary id from sendMessage.

**Comment by GuilhermeAmado** [comment]
> > But it didn't work.
> 
> It should work, what was the error? Note that if you're forwarding a message you just sent, you can't use a temporary id from `sendMessage` in `message_ids`, the id should be received from updates.

I'll check as soon as I get home, but as far as I remember, there was no error on the console, the message never arrives.
Just to be clear on what I am trying to do: Forward every message that gets sent on a group chat to another group. Not only messages sent by me but everyone.

Sorry if it's confusing, english is not my primary language.
Thanks for your time!

**Comment by Bannerets** [comment]
Does `forwardMessages` return a `Messages` object or does it return null? The error also might be in an `updateMessageSendFailed` update. Also look for events in `.on('error')`. Did you get the `chat_id` (and `from_chat_id`) from tdlib or did you type it manually (getting it from external source)?

**Comment by GuilhermeAmado** [comment]
I'm so sorry. There was a bug in my app, now it's working as it should. Every message gets forwarded. Thanks for your help!
